apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsgw
  labels:
    app: wsgw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wsgw
  template:
    metadata:
      labels:
        app: wsgw
    spec:
      containers:
        - name: wsgw
          image: wsgw
          imagePullPolicy: Never
          env:
            - name: LOG_LEVEL
              value: debug
            - name: WSGW_INSTANCE_IPADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WSGW_SERVER_PORT
              value: "8080"
            - name: WSGW_INSTANCE_PROTOCOL
              value: "http"
            - name: WSGW_APP_BASE_URL
              value: "http://wsgw-e2e-app:8080"
            - name: WSGW_OTLP_ENDPOINT
              value: http://alloy.my-grafana.svc.cluster.local:4318
            - name: WSGW_OTLP_SERVICE_NAMESPACE
              value: "bitkit/wsgw"
            - name: WSGW_OTLP_SERVICE_NAME
              value: "wsgw"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "3000m"
            limits:
              memory: "1024Mi"
